import { type NextPage } from 'next';
// Dependencies
import Head from 'next/head';
import Link from 'next/link';
import { useUser, SignOutButton } from '@clerk/nextjs';

// API
import { api } from '~/utils/api';

// Components
import { AuthFooter } from '~/components/AuthFooter';
import { SideNavigation } from '~/components/SideNavigation';
import { NewToTwooter } from '~/components/NewToTwooter';

const Home: NextPage = () => {
  const { data, isLoading } = api.tweet.getAll.useQuery();

  const user = useUser();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen justify-center">
        <SideNavigation />
        <main className="flex grow md:grow-0">
          <div className="w-full max-w-[600px] border-x border-zinc-800 md:w-[600px]">
            {data?.map((tweet) => (
              <div key={tweet.id} className="border-y border-zinc-800 p-8">
                {tweet.text}
              </div>
            ))}
          </div>
          {!user.isSignedIn && <NewToTwooter />}
        </main>
      </div>
      {!user.isSignedIn && <AuthFooter />}
    </>
  );
};

export default Home;
